name: Build

on:
  push:
    branches: [ algoxy ]
  pull_request:
    branches: [ algoxy ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Before build
        run: |
          sed -i 's/SimSun/Noto Serif CJK SC/; s/SimHei/Noto Sans CJK SC/; s/Consolas/FreeMono/' prelude.sty
          sed -i 's/\(\documentclass.*{ctexbook}\)/\1\n\\defaultCJKfontfeatures{Scale=0.962216}/' algoxy-zh-cn.tex
          cat algoxy-zh-cn.tex
